"""
Fibonacci Anyon Algebra Operational Tool - Advanced Dynamics
============================================================
Adding high-level manifold synthesis and braid-group topology.
"""
import numpy as np
import cmath
import math
from m3iosis.extensions import FibonacciExtensions

class FibonacciManifold(FibonacciExtensions):
    
    # 16. Braid Group Generator Word
    def get_generator(self, i, n):
        return [i]
    
    # 17. Braid Group Center (Z(Bn)) (Approximation)
    def braid_center(self, n):
        # Center of Bn is generated by (sigma_1 sigma_2 ... sigma_{n-1})^n
        word = []
        for _ in range(n):
            word.extend(list(range(1, n)))
        return word

    # 18. Full monodromy: the sigma_1^2 exchange
    def monodromy(self, state, num_strands=3):
        """Apply sigma_1 squared, taking one anyon a full turn around another.

        This carried the name `teleport`. It is a legitimate braid and the
        physically meaningful one (full monodromy is what distinguishes anyonic
        statistics from a half-exchange convention), but no state is
        transferred anywhere and there is no entangled resource or classical
        correction, so the teleportation name promised a protocol that is not
        here.
        """
        return self.evaluate_braid_word([1, 1], num_strands) @ state

    # 19. Braid Homotopy (Equality via commutator)
    def are_homotopic(self, w1, w2, n):
        return np.allclose(self.evaluate_braid_word(w1, n), self.evaluate_braid_word(w2, n))

    # 20. Writhe: the SIGNED crossing count
    def writhe(self, word):
        """Sum of crossing signs. A stub here returned `len(word)`, the

        unsigned length, which contradicted the signed sum this same repository
        already computes correctly inside `jones_polynomial`.
        """
        return sum(1 if g > 0 else -1 for g in word)

    # 21. Topological Charge Conservation
    def charge_check(self, state):
        # Measures if state is vacuum or tau-charged
        return self.exp_val(state, np.diag([1, 0]))

    # 22. Anyonic Scattering Matrix
    def S_matrix_element(self, a, b):
        return self.S[a, b]

    # 23. Braid Word Length
    def word_len(self, word): return len(word)

    # 24. First Betti number of the closure complement
    def betti_1(self, word, num_strands):
        """b1 of the complement of the braid closure = number of components.

        For a link complement in S^3, H_1 is free abelian of rank equal to the
        number of components, and the components of a braid closure are the
        cycles of the permutation the word induces. This was set equal to the
        writhe, which is not the Betti number of anything.
        """
        perm = list(range(num_strands))
        for g in word:
            i = abs(g) - 1
            perm[i], perm[i + 1] = perm[i + 1], perm[i]
        seen = set(); cycles = 0
        for start in range(num_strands):
            if start in seen:
                continue
            cycles += 1
            j = start
            while j not in seen:
                seen.add(j); j = perm[j]
        return cycles

    # 25. Braid Group Representation (Rho)
    def rho(self, word, n): return self.evaluate_braid_word(word, n)

    # 26. Braiding Energy (Expectation Value of R)
    def braid_energy(self, state, word, n):
        return self.exp_val(state, self.evaluate_braid_word(word, n))

    # 27. Braid Word Flattening
    def flatten(self, word): return [item for sublist in word for item in sublist] if any(isinstance(i, list) for i in word) else word

    # 28. Determinant of the S-matrix
    def s_matrix_determinant(self):
        """det(S), which for the Fibonacci theory is identically -1.

        This was called `curvature`. A constant carries no geometry, and
        dressing it in that name put a number in clothes it does not wear. The
        constancy is itself the content: S is a symmetric involution up to
        normalization, so its determinant cannot vary.
        """
        return np.linalg.det(self.S)

    # 29. T-Gate Braid
    def T_gate(self): return self.T

    # 30. Anyonic Path Integral Measure
    def path_integral(self, word, n):
        return np.trace(self.evaluate_braid_word(word, n))
